environment:
  core_version: 2.1.0
  GitHubToken:
    secure: Hq962a6/5Qpa9d37AJuVplk7sYc4AYRn9b5dg4eLi1jXBkdvbj2zRsG+8r+4nNE3
image: Visual Studio 2017
version: '$(core_version)+{branch}.{build}'
install:
  - cmd: git submodule update --init --recursive
  - cmd: nuget.exe restore
  - cmd: IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (%UserProfile%\.nuget\packages\squirrel.windows\1.7.8\tools\SyncReleases.exe  --url=https://github.com/poma/Hotsapi.Uploader --token=%GitHubToken%)

assembly_info:
  patch: true
  file: Hotsapi.Uploader.Windows\Properties\AssemblyInfo.cs
  assembly_version: '$(core_version)'
  assembly_file_version: '$(core_version)'
  assembly_informational_version: '{version}'

build_script:
  - msbuild Hotsapi.Uploader.sln -verbosity:minimal /property:Configuration=Zip
  - msbuild Hotsapi.Uploader.sln -verbosity:minimal /property:Configuration=Installer

artifacts:
  - path: Releases\HotsApiUploaderSetup.exe
  - path: Releases\HotsApi.zip
  - path: Releases\RELEASES
  - path: Releases\Hotsapi.Uploader-$(core_version)-full.nupkg
  - path: Releases\Hotsapi.Uploader-$(core_version)-delta.nupkg

deploy:
  - provider: GitHub
    auth_token:
      secure: Hq962a6/5Qpa9d37AJuVplk7sYc4AYRn9b5dg4eLi1jXBkdvbj2zRsG+8r+4nNE3
    repository: poma/Hotsapi.Uploader
    artifact: '/.*/'
    draft: true
    on:
      branch: /^v\d+\.\d+\.\d+/
      appveyor_repo_tag: true

cache:
  - packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - Releases

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/59b5d893e9a21d517d5e
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
