environment:
  core_version: 2.1.0
  GitHubToken:
    secure: 8c58c9a72b8c3cc57186b6e833fe17bf66d70957
image: Visual Studio 2019
version: '$(core_version)+{branch}.{build}'
install:
  - cmd: git submodule update --init --recursive
  - cmd: nuget.exe restore
  - cmd: IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (%UserProfile%\.nuget\packages\squirrel.windows\1.7.8\tools\SyncReleases.exe  --url=https://github.com/Heroes-Profile/HeroesProfile.Uploader --token=%GitHubToken%)

assembly_info:
  patch: true
  file: Heroesprofile.Uploader.Windows\Properties\AssemblyInfo.cs
  assembly_version: '$(core_version)'
  assembly_file_version: '$(core_version)'
  assembly_informational_version: '{version}'

build_script:
  - msbuild Heroesprofile.Uploader.sln -verbosity:minimal /property:Configuration=Zip
  - msbuild Heroesprofile.Uploader.sln -verbosity:minimal /property:Configuration=Installer

artifacts:
  - path: Releases\HeroesprofileUploaderSetup.exe
  - path: Releases\Heroesprofile.zip
  - path: Releases\RELEASES
  - path: Releases\Heroesprofile.Uploader-$(core_version)-full.nupkg
  - path: Releases\Heroesprofile.Uploader-$(core_version)-delta.nupkg

deploy:
  - provider: GitHub
    auth_token:
      secure: 8c58c9a72b8c3cc57186b6e833fe17bf66d70957
    repository: Heroes-Profile/HeroesProfile.Uploader
    artifact: '/.*/'
    draft: true
    on:
      branch: /^v\d+\.\d+\.\d+/
      appveyor_repo_tag: true

cache:
  - packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - Releases

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/59b5d893e9a21d517d5e
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true