// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Heroesprofile.Uploader.Common;
//
//    var uploadResult = UploadResult.FromJson(jsonString);

namespace Heroesprofile.Uploader.Common
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UploadResult
    {
        [JsonProperty("fingerprint")]
        public Guid Fingerprint { get; set; }

        [JsonProperty("replayID")]
        public int ReplayId { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

    public partial class UploadResult
    {
        public static UploadResult FromJson(string json) => JsonConvert.DeserializeObject<UploadResult>(json, Heroesprofile.Uploader.Common.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this UploadResult self) => JsonConvert.SerializeObject(self, Heroesprofile.Uploader.Common.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
